'use strict';
/* ============================================================================
 * Expoline — kiosk mode + digital menu boards.
 *
 * INTEGRATOR: add these lines to server.js (do NOT edit this file's contract):
 *
 *   const kiosk = require('./routes/kiosk');
 *   kiosk.migrate(db);          // place with the other boot-time migrations
 *   // in authMiddleware's public-path early return, add the kiosk paths:
 *   //   if (req.path === '/kiosk/menu'
 *   //       || (req.path === '/kiosk/order' && req.method === 'POST')
 *   //       || (req.path === '/kiosk/call-staff' && req.method === 'POST')
 *   //       || req.path === '/menuboards') return next();
 *   // AFTER app.use('/api', authMiddleware) (the staff call-flag endpoints
 *   // need req.user populated by the wall for their serverPlus role check):
 *   kiosk.register(app, { db, SITE_ID, nowIso, crypto, persistTotals,
 *                          checkResponse, broadcastCheckUpdated, serverPlus });
 *   // Optional (enables real-time KDS push for kiosk orders):
 *   //   pass broadcastTicket too — register() uses ctx.broadcastTicket if present.
 *
 * Design notes:
 * - No new tables except kiosk_calls (staff-call flags). Checks, check_items,
 *   menu_items and kds_tickets are reused; kiosk orders land on a virtual
 *   'KIOSK' table created lazily by ensureKioskTable().
 * - Customer endpoints (/kiosk/menu, /kiosk/order, /kiosk/call-staff,
 *   /menuboards) are intentionally unauthenticated (customer device) but
 *   hardened: per-IP rate limiting, server-side re-pricing (client prices are
 *   never trusted), market-price items excluded, 86'd items excluded.
 * - The STAFF-facing endpoints (GET /kiosk/calls, POST /kiosk/calls/:id/clear)
 *   are server-side role-gated via ctx.serverPlus — an unauthenticated caller
 *   must not read or silently clear staff-call flags.
 * - Kiosk items go straight to state='sent' (fire immediately) with KDS
 *   tickets created via the same station-grouping pattern as the send flow.
 * ========================================================================== */

const nodeCrypto = require('node:crypto');

const KIOSK_TABLE_LABEL = 'KIOSK';
const RATE_LIMIT_MAX = 30;               // max kiosk orders per window per IP
const RATE_LIMIT_WINDOW_MS = 60_000;
const MAX_ITEMS_PER_ORDER = 50;
const MAX_QTY = 20;

const isInt = (v) => Number.isInteger(v);

/* ------------------------------- rate limit ------------------------------ */
const hitsByIp = new Map();
function rateLimited(ip) {
  const now = Date.now();
  let hits = hitsByIp.get(ip);
  if (!hits) { hits = []; hitsByIp.set(ip, hits); }
  while (hits.length && hits[0] <= now - RATE_LIMIT_WINDOW_MS) hits.shift();
  if (hits.length >= RATE_LIMIT_MAX) return true;
  hits.push(now);
  return false;
}
// Prevent unbounded growth of the limiter map.
setInterval(() => {
  const now = Date.now();
  for (const [ip, hits] of hitsByIp) {
    while (hits.length && hits[0] <= now - RATE_LIMIT_WINDOW_MS) hits.shift();
    if (!hits.length) hitsByIp.delete(ip);
  }
}, 5 * 60_000).unref();

function clientIp(req) {
  return req.ip || (req.socket && req.socket.remoteAddress) || 'unknown';
}

/* --------------------------------- migrate -------------------------------- */
function migrate(db) {
  /* Staff-call flags raised from kiosk devices. The floor view polls
     GET /api/kiosk/calls to light up the KIOSK table. */
  db.exec(`CREATE TABLE IF NOT EXISTS kiosk_calls (
    id INTEGER PRIMARY KEY,
    uuid TEXT,
    site_id TEXT,
    table_id INTEGER,
    status TEXT DEFAULT 'active',
    created_at TEXT,
    cleared_at TEXT
  )`);
  const cols = new Set(db.prepare('PRAGMA table_info(kiosk_calls)').all().map((c) => c.name));
  if (!cols.has('uuid')) db.exec('ALTER TABLE kiosk_calls ADD COLUMN uuid TEXT');
  const missing = db.prepare('SELECT id FROM kiosk_calls WHERE uuid IS NULL').all();
  if (missing.length) {
    const upd = db.prepare('UPDATE kiosk_calls SET uuid = ? WHERE id = ?');
    for (const r of missing) upd.run(nodeCrypto.randomUUID(), r.id);
  }
  db.exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_kiosk_calls_uuid ON kiosk_calls(uuid)');
}

function ensureKioskTable(db, SITE_ID) {
  let t = db.prepare('SELECT * FROM tables WHERE site_id = ? AND label = ?').get(SITE_ID, KIOSK_TABLE_LABEL);
  if (!t) {
    const r = db.prepare(
      'INSERT INTO tables (site_id, zone_id, label, seats) VALUES (?, NULL, ?, 1)'
    ).run(SITE_ID, KIOSK_TABLE_LABEL);
    t = db.prepare('SELECT * FROM tables WHERE id = ?').get(r.lastInsertRowid);
  }
  return t;
}

/* ------------------------------ menu building ----------------------------- */
/* One JOIN for categories+items (86'd excluded), one batched query for
   modifiers. `forOrder=true` also drops market-price items (price_cents = 0),
   which a kiosk cannot price without a manager. */
function buildMenu(db, SITE_ID, forOrder, effPrice) {
  const rows = db.prepare(`
    SELECT c.id AS cat_id, c.name AS cat_name, c.sort AS cat_sort,
           i.id, i.name, i.description, i.price_cents, i.hh_price_cents, i.item_type,
           i.station, i.course, i.price_note
      FROM menu_categories c
      JOIN menu_items i ON i.category_id = c.id
     WHERE c.site_id = ? AND i.site_id = ? AND i.active = 1 AND COALESCE(i.is_86, 0) = 0
       ${forOrder ? 'AND i.price_cents > 0' : ''}
     ORDER BY c.sort, c.id, i.id
  `).all(SITE_ID, SITE_ID);

  const itemIds = [...new Set(rows.map((r) => r.id))];
  const modsByItem = new Map();
  if (itemIds.length) {
    const placeholders = itemIds.map(() => '?').join(',');
    for (const m of db.prepare(
      `SELECT item_id, name, price_delta_cents FROM menu_modifiers WHERE item_id IN (${placeholders}) ORDER BY id`
    ).all(...itemIds)) {
      if (!modsByItem.has(m.item_id)) modsByItem.set(m.item_id, []);
      modsByItem.get(m.item_id).push({ name: m.name, price_delta_cents: m.price_delta_cents });
    }
  }

  const cats = [];
  const byCat = new Map();
  for (const r of rows) {
    if (!byCat.has(r.cat_id)) {
      const c = { id: r.cat_id, name: r.cat_name, sort: r.cat_sort, items: [] };
      byCat.set(r.cat_id, c);
      cats.push(c);
    }
    byCat.get(r.cat_id).items.push({
      id: r.id,
      name: r.name,
      description: r.description,
      price_cents: r.price_cents,
      // Happy-hour pricing: what a kiosk order placed right now would
      // actually be charged (the resolver is injected by the host; without
      // it the regular price stands).
      hh_price_cents: r.hh_price_cents != null ? r.hh_price_cents : null,
      effective_price_cents: effPrice ? effPrice(r) : r.price_cents,
      hh_active: effPrice ? effPrice(r) !== r.price_cents : false,
      item_type: r.item_type,
      station: r.station,
      course: r.course,
      price_note: r.price_note,
      modifiers: modsByItem.get(r.id) || [],
    });
  }
  return cats;
}

/* Split categories across N boards; board is 1-indexed. */
function splitBoards(cats, board, boards) {
  const n = Math.max(1, boards | 0);
  const k = Math.min(n, Math.max(1, board | 0));
  const per = Math.ceil(cats.length / n);
  return cats.slice((k - 1) * per, k * per);
}

/* -------------------------------- register -------------------------------- */
function register(app, ctx) {
  const { db, SITE_ID, nowIso, crypto, persistTotals, checkResponse, broadcastCheckUpdated, serverPlus, effectivePriceCents } = ctx;
  // Menu-refresh push for countdown flips this surface causes; older
  // hosts without it simply skip the push (menus still refetch on the
  // next broadcast from any other path).
  const pushMenu = typeof ctx.broadcastMenuUpdated === 'function' ? ctx.broadcastMenuUpdated : () => {};
  const effPrice = typeof effectivePriceCents === 'function' ? effectivePriceCents : null;
  /* Tax snapshot (gap #9): freeze the item's rate/inclusive setting on
     the line at ring time, like the price. Host-injected; the local
     fallback is the identical computation for standalone hosts. */
  const taxSnapOf = typeof ctx.taxSnapshotOf === 'function' ? ctx.taxSnapshotOf : (src) => {
    const ok = !!src && Number.isInteger(src.tax_rate_bps) && src.tax_rate_bps >= 0 && src.tax_rate_bps <= 10000;
    return { tax_rate_bps: ok ? src.tax_rate_bps : null, tax_inclusive: src && src.tax_inclusive ? 1 : 0 };
  };
  // serverPlus is required: the staff-facing call-flag endpoints below must
  // reject unauthenticated/wrong-role callers server-side.
  if (typeof serverPlus !== 'function') throw new Error('kiosk.register requires ctx.serverPlus');

  /* GET /api/kiosk/menu — orderable menu for the kiosk. 86'd items are
     EXCLUDED (not flagged); market-price items excluded (need a manager). */
  app.get('/api/kiosk/menu', (req, res) => {
    res.json({ categories: buildMenu(db, SITE_ID, true, effPrice), generated_at: nowIso() });
  });

  /* POST /api/kiosk/order {items:[{menu_item_id, qty, modifiers:[{name}]}],
     customer_name?} — creates one check on the KIOSK table, fires items
     straight to 'sent' with KDS tickets. No auth (customer device); hardened
     by rate limiting + full server-side validation and re-pricing. */
  app.post('/api/kiosk/order', (req, res) => {
    const ip = clientIp(req);
    if (rateLimited(ip)) {
      return res.status(429).json({ error: 'Too many orders — please wait a moment and try again' });
    }
    const b = req.body || {};
    const items = b.items;
    if (!Array.isArray(items) || !items.length || items.length > MAX_ITEMS_PER_ORDER) {
      return res.status(400).json({ error: `items must be a non-empty array (max ${MAX_ITEMS_PER_ORDER})` });
    }
    const customerName = typeof b.customer_name === 'string' ? b.customer_name.slice(0, 40) : null;

    // Validate + re-price every line server-side. Client prices are ignored.
    const itemStmt = db.prepare('SELECT * FROM menu_items WHERE id = ? AND site_id = ? AND active = 1');
    const modStmt = db.prepare('SELECT price_delta_cents FROM menu_modifiers WHERE item_id = ? AND name = ?');
    const lines = [];
    for (const [idx, it] of items.entries()) {
      if (!it || !isInt(it.menu_item_id)) {
        return res.status(400).json({ error: `items[${idx}].menu_item_id must be an integer` });
      }
      const menuItem = itemStmt.get(it.menu_item_id, SITE_ID);
      if (!menuItem) {
        return res.status(400).json({ error: `items[${idx}]: unknown or unavailable menu item` });
      }
      /* Floor 86 (runtime availability): a sold-out item refuses here
         too, in this surface's established phrasing; the authoritative
         re-check + countdown consume run inside the write transaction
         below (this read can race a floor 86 by design). */
      if (menuItem.is_86) {
        return res.status(400).json({ error: `items[${idx}]: "${menuItem.name}" is 86'd right now` });
      }
      if (!(menuItem.price_cents > 0)) {
        return res.status(400).json({ error: `items[${idx}]: "${menuItem.name}" requires staff pricing` });
      }
      const qty = it.qty === undefined ? 1 : it.qty;
      if (!isInt(qty) || qty < 1 || qty > MAX_QTY) {
        return res.status(400).json({ error: `items[${idx}].qty must be 1–${MAX_QTY}` });
      }
      const mods = it.modifiers === undefined ? [] : it.modifiers;
      if (!Array.isArray(mods)) {
        return res.status(400).json({ error: `items[${idx}].modifiers must be an array` });
      }
      const pricedMods = [];
      for (const m of mods) {
        if (!m || typeof m.name !== 'string' || !m.name.trim()) {
          return res.status(400).json({ error: `items[${idx}]: each modifier needs a name` });
        }
        // Server-side price: look up the canonical modifier; ignore any
        // client-supplied price_delta_cents entirely.
        const row = modStmt.get(menuItem.id, m.name.trim());
        if (!row) {
          return res.status(400).json({ error: `items[${idx}]: unknown modifier "${m.name}" for "${menuItem.name}"` });
        }
        pricedMods.push({ name: m.name.trim(), price_delta_cents: row.price_delta_cents });
      }
      lines.push({ menuItem, qty, modifiers: pricedMods });
    }

    // Phase 1B money audit (concurrency): the entire order write runs in one
    // write transaction with an 86 re-check, so an item 86'd mid-order
    // cannot land on the kiosk check. Broadcasts happen after COMMIT so
    // subscribers never see uncommitted tickets.
    const ids = [...new Set(lines.map((l) => l.menuItem.id))];
    const placeholders = ids.map(() => '?').join(',');
    let checkId;
    let consumedAny86 = false;
    const tickets = [];
    try {
      db.exec('BEGIN IMMEDIATE');
      const recheck = db.prepare(
        `SELECT id, active, is_86, remaining, name, category_id FROM menu_items WHERE id IN (${placeholders})`
      ).all(...ids);
      const activeMap = new Map(recheck.map((r) => [r.id, r.active]));
      for (const [idx, ln] of lines.entries()) {
        if (activeMap.get(ln.menuItem.id) !== 1) {
          db.exec('ROLLBACK');
          return res.status(400).json({ error: `items[${idx}]: "${ln.menuItem.name}" is 86'd right now` });
        }
      }
      /* Floor 86 runtime state, re-checked fresh inside the transaction
         (an item floor-86'd after the validation read refuses here),
         and the countdown consume: aggregated per item across the
         whole order, one conditional UPDATE per item — a lost race
         rolls the order back whole. Reaching zero flips the item to
         sold out, audited as actor 'system' (the count ran out). */
      const freshMap = new Map(recheck.map((r) => [r.id, r]));
      const totals86 = new Map();
      const firstIdx86 = new Map();
      lines.forEach((ln, idx) => {
        totals86.set(ln.menuItem.id, (totals86.get(ln.menuItem.id) || 0) + ln.qty);
        if (!firstIdx86.has(ln.menuItem.id)) firstIdx86.set(ln.menuItem.id, idx);
      });
      for (const [mid, totalQty] of totals86) {
        const fresh = freshMap.get(mid);
        const idx = firstIdx86.get(mid);
        if (fresh.is_86) {
          db.exec('ROLLBACK');
          return res.status(400).json({ error: `items[${idx}]: "${fresh.name}" is 86'd right now` });
        }
        if (fresh.remaining == null) continue;
        if (totalQty > fresh.remaining) {
          db.exec('ROLLBACK');
          return res.status(400).json({ error: `items[${idx}]: "${fresh.name}" has only ${fresh.remaining} left` });
        }
        const dec = db.prepare(
          'UPDATE menu_items SET remaining = remaining - ? WHERE id = ? AND site_id = ? AND remaining IS NOT NULL AND remaining >= ?'
        ).run(totalQty, mid, SITE_ID, totalQty);
        if (dec.changes === 0) {
          db.exec('ROLLBACK');
          return res.status(400).json({ error: `items[${idx}]: "${fresh.name}" is 86'd right now` });
        }
        consumedAny86 = true;
        const after = db.prepare('SELECT remaining FROM menu_items WHERE id = ?').get(mid);
        if (after && after.remaining === 0) {
          db.prepare('UPDATE menu_items SET is_86 = 1 WHERE id = ?').run(mid);
          db.prepare('INSERT INTO menu_audit (site_id, actor, action, item_id, category_id, details, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)')
            .run(SITE_ID, 'system', 'item.86_auto', mid, fresh.category_id != null ? fresh.category_id : null,
              JSON.stringify({ name: fresh.name, via: 'countdown' }), nowIso());
        }
      }
      const kioskTable = ensureKioskTable(db, SITE_ID);
      const at = nowIso();
      checkId = db.prepare(
        "INSERT INTO checks (uuid, site_id, table_id, server_id, tab_name, guest_count, status, opened_at) VALUES (?, ?, ?, NULL, ?, 1, 'open', ?)"
      ).run(crypto.randomUUID(), SITE_ID, kioskTable.id, customerName ? `Kiosk · ${customerName}` : 'Kiosk', at).lastInsertRowid;

      const insItem = db.prepare(
        "INSERT INTO check_items (uuid, check_id, menu_item_id, seat, qty, unit_price_cents, tax_rate_bps, tax_inclusive, modifiers_json, course, state, added_at, sent_at) VALUES (?, ?, ?, 1, ?, ?, ?, ?, ?, ?, 'sent', ?, ?)"
      );
      const byStation = new Map();
      for (const ln of lines) {
        const taxSnap = taxSnapOf(ln.menuItem);
        const r = insItem.run(
          crypto.randomUUID(), checkId, ln.menuItem.id, ln.qty,
          effPrice ? effPrice(ln.menuItem) : ln.menuItem.price_cents, taxSnap.tax_rate_bps, taxSnap.tax_inclusive, JSON.stringify(ln.modifiers), ln.menuItem.course, at, at
        );
        const station = ln.menuItem.station || 'expediter';
        if (!byStation.has(station)) byStation.set(station, []);
        byStation.get(station).push({
          item_id: Number(r.lastInsertRowid),
          name: ln.menuItem.name,
          seat: 1,
          qty: ln.qty,
          modifiers: ln.modifiers,
        });
      }

      // KDS tickets — same station-grouping shape as the send flow.
      const insTicket = db.prepare(
        "INSERT INTO kds_tickets (uuid, check_id, site_id, station, table_label, server_name, items_json, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'new', ?)"
      );
      for (const [station, ticketItems] of byStation) {
        const r = insTicket.run(
          crypto.randomUUID(), checkId, SITE_ID, station,
          KIOSK_TABLE_LABEL, 'Kiosk', JSON.stringify(ticketItems), at
        );
        const row = db.prepare('SELECT * FROM kds_tickets WHERE id = ?').get(r.lastInsertRowid);
        tickets.push({
          id: row.id, uuid: row.uuid, check_id: row.check_id, station: row.station,
          table_label: row.table_label, server_name: row.server_name,
          items: ticketItems, status: row.status, created_at: row.created_at,
        });
      }

      persistTotals(checkId);
      db.exec('COMMIT');
    } catch (e) {
      try { db.exec('ROLLBACK'); } catch { /* already rolled back */ }
      throw e;
    }

    for (const t of tickets) {
      if (typeof ctx.broadcastTicket === 'function') ctx.broadcastTicket(t);
    }
    broadcastCheckUpdated(checkId);
    if (consumedAny86) pushMenu();
    res.status(201).json({ check: checkResponse(checkId), tickets });
  });

  /* POST /api/kiosk/call-staff — big "call staff" button. Raises a flag the
     floor view can see via GET /api/kiosk/calls. */
  app.post('/api/kiosk/call-staff', (req, res) => {
    const kioskTable = ensureKioskTable(db, SITE_ID);
    const at = nowIso();
    // One active call per kiosk table is enough — refresh the existing one.
    const existing = db.prepare(
      "SELECT id FROM kiosk_calls WHERE site_id = ? AND table_id = ? AND status = 'active' ORDER BY id DESC LIMIT 1"
    ).get(SITE_ID, kioskTable.id);
    if (existing) {
      db.prepare('UPDATE kiosk_calls SET created_at = ? WHERE id = ?').run(at, existing.id);
      return res.status(200).json({ id: existing.id, status: 'active', refreshed: true });
    }
    const r = db.prepare(
      "INSERT INTO kiosk_calls (uuid, site_id, table_id, status, created_at) VALUES (?, ?, ?, 'active', ?)"
    ).run(crypto.randomUUID(), SITE_ID, kioskTable.id, at);
    res.status(201).json({ id: r.lastInsertRowid, status: 'active' });
  });

  /* GET /api/kiosk/calls — active staff-call flags (for the staff floor view).
     Staff-only: any authenticated floor role can read; customers must not see
     (or poll) internal staff-call state. */
  app.get('/api/kiosk/calls', serverPlus(), (req, res) => {
    res.json(db.prepare(
      `SELECT kc.id, kc.uuid, kc.table_id, t.label AS table_label, kc.created_at
         FROM kiosk_calls kc JOIN tables t ON t.id = kc.table_id
        WHERE kc.site_id = ? AND kc.status = 'active' ORDER BY kc.created_at`
    ).all(SITE_ID));
  });

  /* POST /api/kiosk/calls/:id/clear — staff clears the flag. Staff-only:
     an unauthenticated caller must not be able to silently drop staff-call
     flags (or the floor view would never light up). */
  app.post('/api/kiosk/calls/:id/clear', serverPlus(), (req, res) => {
    const call = db.prepare('SELECT * FROM kiosk_calls WHERE id = ? AND site_id = ?').get(req.params.id, SITE_ID);
    if (!call) return res.status(404).json({ error: 'Call not found' });
    db.prepare("UPDATE kiosk_calls SET status = 'cleared', cleared_at = ? WHERE id = ?").run(nowIso(), call.id);
    res.json({ id: call.id, status: 'cleared' });
  });

  /* GET /api/menuboards?board=1&boards=1 — TV menu. 86'd items excluded.
     board/boards splits categories across multiple TVs. */
  app.get('/api/menuboards', (req, res) => {
    const cats = buildMenu(db, SITE_ID, false, effPrice);
    const board = parseInt(req.query.board, 10) || 1;
    const boards = parseInt(req.query.boards, 10) || 1;
    res.json({
      board, boards,
      total_categories: cats.length,
      categories: splitBoards(cats, board, boards),
      generated_at: nowIso(),
    });
  });
}

module.exports = { migrate, register };
